[package]
name = "spin-runtime"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
spin-core = { path = "../core" }
spin-domain = { path = "../domain" }
spin-server = { path = "../server" }
spin-store = { path = "../store" }
leanhttp = { git = "https://github.com/xinix00/lean.git", tag = "v3.1.9" }

[lints]
workspace = true
