[package]
name = "spin-server"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
spin-domain = { path = "../domain" }
spin-core = { path = "../core" }
spin-store = { path = "../store" }
spin-security = { path = "../security" }

[lints]
workspace = true
